Feat/pop up stories tests
RoutinelyOrganization/routinely-web-next pull request #21
Opened 2024-07-03 22:29 UTC by diogocaxiado

## Criação do Storybook e Testes para os componentes **Popup**

  - Criação de um novo componente **WarningAction** para representação de popup de avisos:
  
     - Ilustração:
         ![image](https://github.com/RoutinelyOrganization/routinely-web-next/assets/65976610/f2abb778-bc58-4f22-b8de-fa37e177afd0)
         ![image](https://github.com/RoutinelyOrganization/routinely-web-next/assets/65976610/7d43cd06-2860-44bc-9632-f86541b19b5e)
         
     - Propriedades:
        com a prop **button** podendo ser 'primary' ou 'danger'.
        
 - Criação de testes e storybooks para os componentes de popup já existentes anteriormente.

2024-07-05 10:47 UTC, alanSxSx commented
Parece que na reunião semanal disseram que não tem necessidade desse componente. Procede ?

2024-07-05 22:13 UTC, staviasz commented
> Parece que na reunião semanal disseram que não tem necessidade desse componente. Procede ?

o componente continuara sendo necessario, so a mensagem de duplicação que sera removida

2024-07-05 22:18 UTC, staviasz requested changes
A confirmAction e o WarningAction são componentes muito parecidos e podem ser apenas um unico componente.

Ajuste para ter apenas um componente

2024-07-11 17:30 UTC, diogocaxiado commented
## Ajustado!

Alterei para a criação de um novo componente chamado Action, efetuasse as duas ações conforme o uso das propriedades.

2024-08-14 18:49 UTC, closed without merging