FEAT: Creating button tests and stories
RoutinelyOrganization/routinely-web-next pull request #4
Opened 2024-06-18 15:44 UTC by alanSxSx

2024-06-18 22:27 UTC, alanSxSx commented
Subi um novo commit atualizando os testes pra passarem, e também adicionando mais teste e mais um storybook

2024-06-19 03:35 UTC, staviasz requested changes
deixei os comentarios no codigo

2024-06-19 03:35 UTC, staviasz commented on src/components/buttons/ButtonBackPage/test.spec.tsx
> +
troca esse mock por jest.mock('next/image') no jest.setup.js

2024-06-19 03:35 UTC, staviasz commented on src/components/buttons/ButtonDownloadApp/stories.tsx
arruma a formatação

2024-06-19 03:35 UTC, staviasz commented on src/components/buttons/ButtonDownloadApp/test.spec.tsx
> +}));
se adicionar a alteração do mock que solicitei acima pode retirar esses moks

2024-06-19 03:35 UTC, staviasz commented on src/components/buttons/ButtonEdit/test.spec.tsx
> +jest.mock('next/image', () => ({
se adicionar a alteração do mock que solicitei acima pode retirar esses moks

2024-06-19 03:35 UTC, staviasz commented on src/components/buttons/ButtonEdit/stories.tsx
ajuste a formatação

2024-06-19 10:38 UTC, alanSxSx commented
Foram feitas as alterações. Solicito nova revisão. Qualquer coisa estou a disposição. Mais uma vez agradeço o feedback !

2024-06-19 21:29 UTC, staviasz approved these changes

2024-06-19 21:30 UTC, merged