FEAT: Create a storybook and tests for Logo components
RoutinelyOrganization/routinely-web-next pull request #6
Opened 2024-06-21 20:35 UTC by diogocaxiado

## Alterações no componente Logo

- Criação do storybook para o `<Logo />`
- Implementando testes para o `<Logo />`
- Tratamento da responsividade

## Alterações no componente LogoShared

- Criação do storybook para o `<LogoShared />`
- Implementando testes para o `<LogoShared />`
- Tratamento da responsividade

2024-06-22 02:36 UTC, staviasz requested changes
Faz um pull da dev e atualiza os tests, alem disso nos arquivos de teste coloca o nome do componente no nome do arquivo Ex: Logo.spec.tsx

2024-06-22 02:36 UTC, staviasz commented on src/components/logos/Logo/test.spec.tsx
> +jest.unmock('next/image');
adicionei um mock global para as imagens, so fazer um pull da dev e pode retirar esses moks

2024-06-22 02:36 UTC, staviasz commented on src/components/logos/Logo/test.spec.tsx
> +  it('should render Logo component with correct src', () => {
testes com src vao falhar posi o mock retorna o svg original e não o passado pelo mock

2024-06-24 11:19 UTC, alanSxSx commented
Parece que está dando conflito com o arquivo .storybook/preview.ts. Tem que resolver o conflito, não é @staviasz ?

2024-06-24 15:35 UTC, diogocaxiado commented
Resolvido o conflito do arquivo .storybook/preview.ts com a atualização dos dados da branch `dev`. Estava ocorrendo o problema por conta de duplicação de arquivo nesta branch existia o arquivo `preview.ts` enquanto na branch `dev` estava presente o arquivo `preview.tsx`. Com a atualização da branch foi solucionado.

Acredito que esteja tudo nos conformes para o merge

2024-06-24 16:34 UTC, alanSxSx approved these changes
Por mim está tudo OK. Vou deixar para o Erick conferir também e dar o Marge.

2024-06-24 19:12 UTC, staviasz approved these changes

2024-06-24 19:12 UTC, merged